spring:
  profiles:
    active: vm
  application:
    name: my-common-util

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  config: classpath:logback-spring.xml

management:
  server:
    port: 8081  # 设置Actuator端口为独立端口，例如8081
  endpoints:
    web:
      exposure:
        include: 'health, info, metrics, prometheus'
      base-path: '/my' # Optional, defaults to /actuator
  metrics:
    web:
      server:
        auto-time-requests: true # Optional, automatically time web requests and expose metrics for them.

executeOnceTaskEnable: true
#executeOnceTaskEnable: false